
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInput;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import jdk.nashorn.internal.scripts.JO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargar();
        cargaralbum();
        System.out.println(listausuarios);
        System.out.println(listalbums);
        menuuser.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingresar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jt_ingresar = new javax.swing.JTextField();
        pf_ingresar = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jd_crear = new javax.swing.JDialog();
        sp_edad = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        jt_user = new javax.swing.JTextField();
        pf_contra = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cancion = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_album = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        crearcancion = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt_cancion = new javax.swing.JTextField();
        sp_duracion = new javax.swing.JSpinner();
        cb_genero = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jl_artista = new javax.swing.JLabel();
        crearalbum = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jt_nombrealbum = new javax.swing.JTextField();
        jt_artistaalbum = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Listaralbum = new javax.swing.JDialog();
        cb_listar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_lista = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Favoritos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_favo = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        CrearPlaylist = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jt_playlist = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        agregarfavo = new javax.swing.JDialog();
        cb_play = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        plays = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jd_rep = new javax.swing.JDialog();
        jl_tiempo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuuser = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jLabel6.setText("Usuario ");

        jLabel7.setText("Contraseña");

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ingresar");

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ingresarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_ingresarLayout.createSequentialGroup()
                        .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_ingresar)
                            .addComponent(pf_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_ingresarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton2)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pf_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(30, 30, 30))
        );

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creacion de Usuario");

        jLabel2.setText("Nombre");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Edad");

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_user))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_contra)
                            .addGroup(jd_crearLayout.createSequentialGroup()
                                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_album.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre de album"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_album.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_albumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_album);

        jButton3.setText("Seleccionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cancionLayout = new javax.swing.GroupLayout(cancion.getContentPane());
        cancion.getContentPane().setLayout(cancionLayout);
        cancionLayout.setHorizontalGroup(
            cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cancionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(151, 151, 151))
        );
        cancionLayout.setVerticalGroup(
            cancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancionLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
        );

        jLabel9.setText("Nombre");

        jLabel10.setText("Artista");

        jLabel11.setText("Duracion");

        jLabel12.setText("Genero");

        sp_duracion.setModel(new javax.swing.SpinnerNumberModel(10L, 10L, null, 1L));

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pop", "Rock", "Reggaeton", "Cumbia", "Salsa", "Reggae", "Merengue", "Jazz" }));

        jButton4.setText("Crear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearcancionLayout = new javax.swing.GroupLayout(crearcancion.getContentPane());
        crearcancion.getContentPane().setLayout(crearcancionLayout);
        crearcancionLayout.setHorizontalGroup(
            crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearcancionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGroup(crearcancionLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(5, 5, 5)))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_genero, 0, 133, Short.MAX_VALUE)
                    .addComponent(jl_artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_duracion)
                    .addComponent(jt_cancion))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearcancionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(84, 84, 84))
        );
        crearcancionLayout.setVerticalGroup(
            crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearcancionLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jt_cancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jl_artista, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel13.setText("Creacion de album");

        jLabel14.setText("Nombre");

        jLabel15.setText("Artista");

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearalbumLayout = new javax.swing.GroupLayout(crearalbum.getContentPane());
        crearalbum.getContentPane().setLayout(crearalbumLayout);
        crearalbumLayout.setHorizontalGroup(
            crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearalbumLayout.createSequentialGroup()
                .addGroup(crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearalbumLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(35, 35, 35)
                        .addGroup(crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_nombrealbum)
                            .addComponent(jt_artistaalbum, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                    .addGroup(crearalbumLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearalbumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crearalbumLayout.setVerticalGroup(
            crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearalbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jt_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jt_artistaalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cb_listar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_listarItemStateChanged(evt);
            }
        });

        jt_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Duracion", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_listaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_lista);

        jButton6.setText("Agregar favoritos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Agregar Playlist");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Eliminar");

        javax.swing.GroupLayout ListaralbumLayout = new javax.swing.GroupLayout(Listaralbum.getContentPane());
        Listaralbum.getContentPane().setLayout(ListaralbumLayout);
        ListaralbumLayout.setHorizontalGroup(
            ListaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaralbumLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaralbumLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(ListaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListaralbumLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ListaralbumLayout.setVerticalGroup(
            ListaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaralbumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListaralbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jt_favo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Canciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_favo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_favoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_favo);

        jButton11.setText("Reproducir");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FavoritosLayout = new javax.swing.GroupLayout(Favoritos.getContentPane());
        Favoritos.getContentPane().setLayout(FavoritosLayout);
        FavoritosLayout.setHorizontalGroup(
            FavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FavoritosLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(139, 139, 139))
        );
        FavoritosLayout.setVerticalGroup(
            FavoritosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FavoritosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel16.setText("Creacion de PlayList");

        jLabel17.setText("Nombre");

        jt_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_playlistActionPerformed(evt);
            }
        });

        jButton9.setText("Crear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearPlaylistLayout = new javax.swing.GroupLayout(CrearPlaylist.getContentPane());
        CrearPlaylist.getContentPane().setLayout(CrearPlaylistLayout);
        CrearPlaylistLayout.setHorizontalGroup(
            CrearPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearPlaylistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearPlaylistLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(CrearPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        CrearPlaylistLayout.setVerticalGroup(
            CrearPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearPlaylistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(CrearPlaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jt_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton9)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jButton10.setText("Crear");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel18.setText("PlayList");

        javax.swing.GroupLayout agregarfavoLayout = new javax.swing.GroupLayout(agregarfavo.getContentPane());
        agregarfavo.getContentPane().setLayout(agregarfavoLayout);
        agregarfavoLayout.setHorizontalGroup(
            agregarfavoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarfavoLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(agregarfavoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_play, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(agregarfavoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarfavoLayout.setVerticalGroup(
            agregarfavoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarfavoLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addComponent(cb_play, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton10)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jTree1);

        javax.swing.GroupLayout playsLayout = new javax.swing.GroupLayout(plays.getContentPane());
        plays.getContentPane().setLayout(playsLayout);
        playsLayout.setHorizontalGroup(
            playsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playsLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        playsLayout.setVerticalGroup(
            playsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playsLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_repLayout = new javax.swing.GroupLayout(jd_rep.getContentPane());
        jd_rep.getContentPane().setLayout(jd_repLayout);
        jd_repLayout.setHorizontalGroup(
            jd_repLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_repLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jl_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jd_repLayout.setVerticalGroup(
            jd_repLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_repLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jl_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Menu");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ingresar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Usuario");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cargar Usuario");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Canciones");

        jMenuItem5.setText("Crear cancion");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Albumes");

        jMenuItem11.setText("Crear Album");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem13.setText("Listar Album");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem12.setText("Eliminar Album");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        menuuser.setText("Usuario");

        jMenuItem7.setText("Explorar");
        menuuser.add(jMenuItem7);

        jMenuItem8.setText("Crear PlayList");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuuser.add(jMenuItem8);

        jMenuItem9.setText("Listar PlayList");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuuser.add(jMenuItem9);

        jMenuItem10.setText("Favoritos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuuser.add(jMenuItem10);

        jMenuItem6.setText("Salir");
        menuuser.add(jMenuItem6);

        jMenuBar1.add(menuuser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((jt_nombre.getText().length() > 0) && (jt_user.getText().length() > 0) && (pf_contra.getText().length() > 0)) {
            String nombre = jt_nombre.getText();
            String contraseña = pf_contra.getText();
            String username = jt_user.getText();
            int edad = (Integer) sp_edad.getValue();
            Usuario u = new Usuario(nombre, edad, username, contraseña);
            listausuarios.add(u);
            agregar();
            agregar1();
            jt_nombre.setText("");
            jt_user.setText("");
            pf_contra.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No puede tener Usuario, contraseña o nombre");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String user = jt_ingresar.getText();
        String password = pf_ingresar.getText();
        for (Usuario li : listausuarios) {
            if ((li.getUsername().equals(user)) && (li.getPassword().equals(password))) {
                login = li;
                jt_ingresar.setText("");
                pf_ingresar.setText("");
                menuuser.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Ha ingresado");
                jd_ingresar.dispose();

            }
        }
        jt_ingresar.setText("");
        pf_ingresar.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd_crear.setModal(true);
        jd_crear.pack();
        jd_crear.setLocationRelativeTo(this);
        jd_crear.setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jd_ingresar.setModal(true);
        jd_ingresar.pack();
        jd_ingresar.setLocationRelativeTo(this);
        jd_ingresar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (listalbums.size() > 0) {
            DefaultTableModel model = (DefaultTableModel) jt_album.getModel();
            int ros = model.getRowCount();
            for (int i = 0; i < ros; i++) {
                model.removeRow(0);
            }
            for (Album li : listalbums) {
                Album[] row = {li};
                model.addRow(row);
            }
            jt_album.setModel(model);
            cancion.setModal(true);
            cancion.pack();
            cancion.setLocationRelativeTo(this);
            cancion.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jt_albumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_albumMouseClicked
        int rsd = jt_album.getSelectedRow();
        albus = (Album) jt_album.getValueAt(rsd, 0);

    }//GEN-LAST:event_jt_albumMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (albus != null) {
            crearcancion.setModal(true);
            crearcancion.pack();
            crearcancion.setLocationRelativeTo(this);
            jl_artista.setText(albus.getArtista());
            crearcancion.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nombre = jt_cancion.getText();
        Long duracion = (Long) sp_duracion.getValue();
        String artista = jl_artista.getText();
        String genero = cb_genero.getSelectedItem().toString();
        Cancion c = new Cancion(albus, nombre, duracion, artista, genero);
        for (Album li : listalbums) {
            if (li.getNombre().equals(albus.getNombre())) {
                li.getListas().add(c);
                JOptionPane.showMessageDialog(this, "Se guardo exitosamente la cancion");
            }
        }
        jt_cancion.setText("");
        jl_artista.setText("");
        crearcancion.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if ((jt_nombrealbum.getText().length() > 0) && (jt_artistaalbum.getText().length() > 0)) {
            String nombre = jt_nombrealbum.getText();
            String artista = jt_artistaalbum.getText();
            Album al = new Album(nombre, artista);
            listalbums.add(al);
            agregar();
            agregar1();
            jt_nombrealbum.setText("");
            jt_artistaalbum.setText("");
            System.out.println(al);
            crearalbum.dispose();
        }
        jt_nombrealbum.setText("");
        jt_artistaalbum.setText("");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        crearalbum.setModal(true);
        crearalbum.pack();
        crearalbum.setLocationRelativeTo(this);
        crearalbum.setVisible(true);

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void cb_listarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_listarItemStateChanged
        if (evt.getStateChange() == 1) {
            Album b = (Album) cb_listar.getSelectedItem();
            DefaultTableModel model = (DefaultTableModel) jt_lista.getModel();
            int ros = model.getRowCount();
            for (int i = 0; i < ros; i++) {
                model.removeRow(0);
            }
            jt_lista.setModel(model);
            for (Cancion lista : b.getListas()) {
                Cancion[] c = {lista};
                model.addRow(c);
            }
            jt_lista.setModel(model);
        }

    }//GEN-LAST:event_cb_listarItemStateChanged

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        cb_listar.setModel(new DefaultComboBoxModel(listalbums.toArray()));
        Listaralbum.setModal(true);
        Listaralbum.pack();
        Listaralbum.setLocationRelativeTo(this);
        Listaralbum.setVisible(true);


    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (index > -1) {

            Cancion nombre = (Cancion) jt_lista.getValueAt(index, 0);
            for (Album l : listalbums) {
                for (Cancion lista : l.getListas()) {
                    if (lista.getNombre().equals(nombre.getNombre())) {
                        ca = lista;
                    }
                }
            }
            System.out.println(ca);
            for (Usuario l : listausuarios) {
                if (l.getNombre().equals(login.getNombre())) {
                    l.getFavoritos().add(ca);
                }
            }
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jt_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listaMouseClicked
        index = jt_lista.getSelectedRow();
        System.out.println(index);
    }//GEN-LAST:event_jt_listaMouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jt_favo.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(0);
        }
        for (Usuario lis : listausuarios) {
            if (lis.equals(login)) {
                for (Cancion fav : lis.getFavoritos()) {
                    Cancion[] sc = {fav};
                    model.addRow(sc);
                }
                jt_favo.setModel(model);
            }
        }
        Favoritos.setModal(true);
        Favoritos.pack();
        Favoritos.setLocationRelativeTo(this);
        Favoritos.setVisible(true);

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jt_playlist.getText().length() > 0) {
            String nombre = jt_playlist.getText();
            Playlist p = new Playlist(nombre);
            jt_playlist.setText("");
            for (Usuario li : listausuarios) {
                if (li.getNombre().equals(login.getNombre())) {
                    li.getListas().add(p);
                }
            }
            agregar();
            CrearPlaylist.dispose();

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (index > -1) {
            int ind = -1;
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb_play.getModel();
            model.removeAllElements();
            ca = (Cancion) jt_lista.getValueAt(index, 0);
            for (Usuario l : listausuarios) {
                if (l.getUsername().equals(login.getUsername())) {
                    ind = l.getListas().size();
                    for (Playlist lista : l.getListas()) {
                        model.addElement(lista);

                    }
                    cb_play.setModel(model);
                }
            }
            if (ind > -1) {
                agregarfavo.setModal(true);
                agregarfavo.pack();
                agregarfavo.setLocationRelativeTo(this);
                agregarfavo.setVisible(true);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CrearPlaylist.setModal(true);
        CrearPlaylist.pack();
        CrearPlaylist.setLocationRelativeTo(this);
        CrearPlaylist.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //DefaultMutableTreeNode model = new DefaultMutableTreeNode("PlayList");
        DefaultTreeModel modelo = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode nodoraiz = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode p;
        DefaultMutableTreeNode d;
        for (Usuario li : listausuarios) {
            if (li.getUsername().equals(login.getUsername())) {
                for (Playlist lista : li.getListas()) {
                    d = new DefaultMutableTreeNode(lista);
                    for (Cancion cancion1 : lista.getLista()) {
                        p = new DefaultMutableTreeNode(cancion1);
                        System.out.println(cancion1);
                        d.add(p);
                    }
                    nodoraiz.add(d);
                }

            }
        }

        modelo.reload();
        plays.setModal(true);
        plays.pack();
        plays.setLocationRelativeTo(this);
        plays.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jt_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_playlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_playlistActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        p = (Playlist) cb_play.getSelectedItem();
        for (Usuario l : listausuarios) {
            if (l.getUsername().equals(login.getUsername())) {
                for (Playlist lista : l.getListas()) {
                    if (lista.getNombre().equals(p.getNombre())) {
                        lista.getLista().add(ca);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jt_favoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_favoMouseClicked
        if (jt_favo.getSelectedRow() > -1) {
            ca = (Cancion) jt_lista.getValueAt(jt_favo.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_jt_favoMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        hilo h = new hilo(jl_tiempo, ca, jd_rep);
        h.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog CrearPlaylist;
    private javax.swing.JDialog Favoritos;
    private javax.swing.JDialog Listaralbum;
    private javax.swing.JDialog agregarfavo;
    private javax.swing.JDialog cancion;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_listar;
    private javax.swing.JComboBox<String> cb_play;
    private javax.swing.JDialog crearalbum;
    private javax.swing.JDialog crearcancion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTree jTree1;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JDialog jd_rep;
    private javax.swing.JLabel jl_artista;
    private javax.swing.JLabel jl_tiempo;
    private javax.swing.JTable jt_album;
    private javax.swing.JTextField jt_artistaalbum;
    private javax.swing.JTextField jt_cancion;
    private javax.swing.JTable jt_favo;
    private javax.swing.JTextField jt_ingresar;
    private javax.swing.JTable jt_lista;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_nombrealbum;
    private javax.swing.JTextField jt_playlist;
    private javax.swing.JTextField jt_user;
    private javax.swing.JMenu menuuser;
    private javax.swing.JPasswordField pf_contra;
    private javax.swing.JPasswordField pf_ingresar;
    private javax.swing.JDialog plays;
    private javax.swing.JSpinner sp_duracion;
    private javax.swing.JSpinner sp_edad;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> listausuarios = new ArrayList();
    ArrayList<Album> listalbums = new ArrayList();
    Usuario login;
    Album albus;
    int index;
    Cancion ca = null;
    Playlist p;

    public void cargar() {
        File f = new File("./usuarios.fac");
        Usuario us = null;
        try {
            if (f.exists()) {
                FileInputStream entrada = new FileInputStream(f);
                ObjectInputStream objeto = new ObjectInputStream(entrada);

                try {
                    while ((us = (Usuario) objeto.readObject()) != null) {
                        listausuarios.add(us);

                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }

    public void cargaralbum() {
        File f = new File("./albumes.fac");
        Album al = null;
        try {
            if (f.exists()) {
                FileInputStream entrada = new FileInputStream(f);
                ObjectInputStream objeto = new ObjectInputStream(entrada);

                try {
                    while ((al = (Album) objeto.readObject()) != null) {
                        listalbums.add(al);

                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
        }
    }

    public void agregar() {
        File f = new File("./albumes.fac");
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(f);
            bw = new ObjectOutputStream(fw);
            try {
                for (Album li : listalbums) {
                    bw.writeObject(li);
                }
                bw.flush();
                try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {

        }

    }

    public void agregar1() {

        File f = new File("./usuarios.fac");
        FileOutputStream fw;
        ObjectOutputStream bw;
        try {
            fw = new FileOutputStream(f);
            bw = new ObjectOutputStream(fw);
            try {
                for (Usuario li : listausuarios) {
                    bw.writeObject(li);
                }
                bw.flush();
                try {
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                }
            } catch (Exception e) {
            }
        } catch (Exception e) {
        }
    }
}
